// <auto-generated>
// Rewired Constants
// This list was generated on 1/25/2025 8:33:05 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Action0")]
        public const int MoveAxis = 0;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Jump")]
        public const int Jump = 1;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Interact")]
        public const int Interact = 2;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Chew")]
        public const int Chew = 3;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Throw Vertical Axis")]
        public const int ThrowVertical = 4;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Throw Horizontal Axis")]
        public const int ThrowHorizontal = 5;
        
        // Menu
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "MenuAxisX")]
        public const int MenuAxisX = 6;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "MenuAxisY")]
        public const int MenuAxisY = 7;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "MenuAxisScroll")]
        public const int MenuAxisScroll = 10;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "MenuAccept")]
        public const int MenuAccept = 8;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "MenuBack")]
        public const int MenuBack = 9;
        
    }
}
